### ISSUE TITLE
Update Redis how-to with SSL/TLS instructions now clients have native support

### ISSUE THREAD

**Issue by edmorley** [RedisLabs/rldocs#3]
Previously traffic had to be wrapped using stunnel:
https://redislabs.com/blog/using-stunnel-to-secure-redis

Now multiple Redis clients have support TLS natively:
https://redislabs.com/blog/secure-redis-ssl-added-to-redsmin-and-clients

It would be great to mention this explicitly in the Redis how-to.

Thanks!

**Comment by itamarhaber** [comment]
Hi Ed,

Except for outstanding errata, the [howto](https://redislabs.com/redis-howto)'s pretty much kept up-to-date w/ the clients' releases in terms of SSL support. Is there a specific client that I'm missing?

**Comment by edmorley** [comment]
Ah my bad, I used GitHub code search for "ssl" on this repo (mainly for the memcache side), and it only returned one hit, but that's just GitHub search being its usual helpful self. I see the rest are documented.

Sorry for the noise! :-)
